language: python
env:
  matrix:
    - PYTHON=2.7 SHAPELY=true
    - PYTHON=2.7 SHAPELY=false
    - PYTHON=3.4 SHAPELY=true
    - PYTHON=3.5 SHAPELY=true
    - PYTHON=3.5 SHAPELY=false

install:
  - if [[ "$PYTHON" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels pandas
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON pip nose
  - source activate test-environment
  - if [[ "$SHAPELY" == "true" ]]; then
      conda install numpy scipy pandas shapely fiona matplotlib;
    fi
  - python -m pip install flake8 python-coveralls coverage
  - python setup.py install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - nosetests --with-coverage --cover-package=cesiumpy
  - flake8 --ignore E501 cesiumpy

after_success:
  - coveralls

